[package]
name = "unet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
log = "0.4.22"
nix = { version = "0.29.0", features = ["ioctl", "socket"] }
signal-hook = "0.3.17"
